/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mt.ui.form;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import javax.swing.JFrame;
import javax.swing.Painter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import mt.util.ComUtil;

/**
 *
 * @author John
 */
public class SplashForm extends javax.swing.JFrame {

    /**
     * Creates new form SplashFrame
     */
    public SplashForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jProgressBarLoading = new javax.swing.JProgressBar();
        jLabelLoaing = new javax.swing.JLabel();
        jLabelMark = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(2, 14, 26));
        setBounds(new java.awt.Rectangle(0, 0, 1280, 800));
        setForeground(new java.awt.Color(2, 14, 26));
        setResizable(false);
        setUndecorated(true);

        jPanelMain.setBackground(new java.awt.Color(2, 14, 26));
        jPanelMain.setForeground(new java.awt.Color(2, 14, 26));

        jProgressBarLoading.setBackground(new java.awt.Color(35, 43, 44));
        jProgressBarLoading.setForeground(new java.awt.Color(0, 204, 0));
        jProgressBarLoading.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jProgressBarLoading.setName(""); // NOI18N
        jProgressBarLoading.setPreferredSize(new java.awt.Dimension(146, 25));

        jLabelLoaing.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabelLoaing.setForeground(new java.awt.Color(170, 191, 53));
        jLabelLoaing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoaing.setText("L O A D I N G");

        jLabelMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_mark.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jProgressBarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(jLabelLoaing, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(jLabelMark, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabelMark, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jProgressBarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(jLabelLoaing))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    
    public void init() {        
        /*UIManager.put("ProgressBar.selectionBackground", Color.black);
        UIManager.put("ProgressBar.selectionForeground", Color.white);
        UIManager.put("ProgressBar.foreground", new Color(8, 32, 128));*/  
        
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        
        
        
    }
    
    public void performProgress() {
        try {   
            Thread.sleep(1000);
            for (int i = 0; i <= 100; i++) {
             Thread.sleep(20);
             jProgressBarLoading.setValue(i);             
            }            
        } catch (Exception e) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLoaing;
    private javax.swing.JLabel jLabelMark;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JProgressBar jProgressBarLoading;
    // End of variables declaration//GEN-END:variables
}
