/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mt.ui.panel;

import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import mt.util.ComUtil;
import mt.util.Def;

/**
 *
 * @author John
 */
public class ContentDashPanel extends javax.swing.JPanel {

    public static final int DEF_PANEL_WIDTH = 1072;
    public static final int DEF_PANEL_HEIGHT = 1018;

    public TitlePanel titlePanel;
    public MatchPanel checkMatchPanel;
    public MatchPanel teamMatchPanel;
    public GamePanel[] gamePanel = new GamePanel[4];

    /**
     * Creates new form ContentPanel
     */
    public ContentDashPanel() {
        initComponents();

        refreshSize(Def.RT_PANEL_CONTENT);
        //init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTour = new javax.swing.JLabel();
        jSeparatorTour = new javax.swing.JSeparator();
        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleShow = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 14, 26));
        setLayout(null);

        jLabelTour.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabelTour.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTour.setText("Tournament List");
        add(jLabelTour);
        jLabelTour.setBounds(52, 670, 270, 35);
        add(jSeparatorTour);
        jSeparatorTour.setBounds(52, 644, 952, 3);
        jSeparatorTour.getAccessibleContext().setAccessibleName("");

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Dashboard");
        add(jLabelTitle);
        jLabelTitle.setBounds(80, 34, 155, 40);

        jLabelTitleShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitleShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_titleshow.png"))); // NOI18N
        jLabelTitleShow.setText("jLabel1");
        add(jLabelTitleShow);
        jLabelTitleShow.setBounds(52, 25, 331, 63);
    }// </editor-fold>//GEN-END:initComponents


    public void refreshSize(Rectangle rtArea) {
        
        float rateW = Def.rateW;
        float rateH = Def.rateH;

        rtArea = ComUtil.getResize(rtArea, rateW, rateH);
        setBounds(rtArea);

        Rectangle rtTour = jLabelTour.getBounds();
        Rectangle rtSeprator = jSeparatorTour.getBounds();
        Rectangle rtTitle = jLabelTitle.getBounds();
        Rectangle rtTitleShow = jLabelTitleShow.getBounds();

        rtTour = ComUtil.getResize(rtTour, rateW, rateH);
        rtSeprator = ComUtil.getResize(rtSeprator, rateW, rateH);
        rtTitle = ComUtil.getResize(rtTitle, rateW, rateH);
        rtTitleShow = ComUtil.getResize(rtTitleShow, rateW, rateH);

        jLabelTour.setBounds(rtTour);
        jSeparatorTour.setBounds(rtSeprator);
        jLabelTitle.setBounds(rtTitle);
        jLabelTitleShow.setBounds(rtTitleShow);

        // title image
        ImageIcon imgIcon = (ImageIcon)jLabelTitleShow.getIcon();
        Image image = imgIcon.getImage();
        Image image2 = image.getScaledInstance(jLabelTitleShow.getWidth(), jLabelTitleShow.getHeight(), Image.SCALE_SMOOTH);
        jLabelTitleShow.setIcon(new ImageIcon(image2));

        // subpanels
        init();

    }

    public void init() {
        // title panel
        titlePanel = new TitlePanel();
        titlePanel.refreshSize(Def.RT_DASH_TITLE);
        add(titlePanel);

        // match panel
        checkMatchPanel = new MatchPanel();
        checkMatchPanel.refreshSize(Def.RT_MATCH1);
        add(checkMatchPanel);

        ImageIcon imgIcon1 = new javax.swing.ImageIcon(getClass().getResource("/resources/ico_man.png"));
        teamMatchPanel = new MatchPanel("Your Team", "Jeremy Packer", "Manage", imgIcon1.getImage(), false);
        teamMatchPanel.refreshSize(Def.RT_MATCH2);
        add(teamMatchPanel);

        // game items
        gamePanel[0] = new GamePanel();//(null, "Fortnite Challangle", "4 Feb | 11 AM", 5000);
        gamePanel[0].refreshSize(Def.RT_GAME_ITEM1);
        add(gamePanel[0]);

        ImageIcon imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_super_mario.jpg"));
        gamePanel[1] = new GamePanel(imgIcon.getImage(), "Super Mario Bros", "5 Feb | 1 PM", 2500);
        gamePanel[1].refreshSize(Def.RT_GAME_ITEM2);
        add(gamePanel[1]);

        imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_dota2.jpg"));
        gamePanel[2] = new GamePanel(imgIcon.getImage(), "Dota 2", "7 Feb | 1:30 AM", 15000);
        gamePanel[2].refreshSize(Def.RT_GAME_ITEM3);
        add(gamePanel[2]);

        imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_broy.jpg"));
        gamePanel[3] = new GamePanel(imgIcon.getImage(), "Fortnite Chanllange", "4 Feb | 11 AM", 3500);
        gamePanel[3].refreshSize(Def.RT_GAME_ITEM4);
        add(gamePanel[3]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleShow;
    private javax.swing.JLabel jLabelTour;
    private javax.swing.JSeparator jSeparatorTour;
    // End of variables declaration//GEN-END:variables
}
