/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyMatchPanel.java
 *
 * Created on Dec 28, 2019, 3:11:57 AM
 */

package mt.ui.panel;

import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import mt.util.ComUtil;
import mt.util.Def;

/**
 *
 * @author Administrator
 */
public class ContentMyMatchPanel extends javax.swing.JPanel {
    public static final int DEF_PANEL_WIDTH = 1072;
    public static final int DEF_PANEL_HEIGHT = 1018;

    /** Creates new form MyMatchPanel */
    public ContentMyMatchPanel() {
        initComponents();

        refreshSize(Def.RT_PANEL_CONTENT);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleShow = new javax.swing.JLabel();
        jLabelOther = new javax.swing.JLabel();
        jLabelYou = new javax.swing.JLabel();
        jButtonScore = new javax.swing.JButton();
        jButtonError = new javax.swing.JButton();
        jLabelLine = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jLabelScoreBg = new javax.swing.JLabel();
        jLabelErrorBg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 14, 26));
        setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("My Match");
        add(jLabelTitle);
        jLabelTitle.setBounds(80, 34, 155, 40);

        jLabelTitleShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitleShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_titleshow.png"))); // NOI18N
        jLabelTitleShow.setText("jLabel1");
        add(jLabelTitleShow);
        jLabelTitleShow.setBounds(52, 25, 331, 63);

        jLabelOther.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelOther.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOther.setText("Hertics");
        add(jLabelOther);
        jLabelOther.setBounds(160, 150, 140, 50);

        jLabelYou.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelYou.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYou.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelYou.setText("You");
        add(jLabelYou);
        jLabelYou.setBounds(560, 150, 70, 50);

        jButtonScore.setBackground(new java.awt.Color(170, 191, 53));
        jButtonScore.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonScore.setForeground(new java.awt.Color(2, 14, 26));
        jButtonScore.setLabel("Start");
        add(jButtonScore);
        jButtonScore.setBounds(654, 282, 103, 43);

        jButtonError.setBackground(new java.awt.Color(170, 191, 53));
        jButtonError.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonError.setForeground(new java.awt.Color(2, 14, 26));
        jButtonError.setLabel("Start");
        jButtonError.setOpaque(false);
        add(jButtonError);
        jButtonError.setBounds(654, 414, 103, 43);

        jLabelLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_mymatch_line.png"))); // NOI18N
        add(jLabelLine);
        jLabelLine.setBounds(52, 121, 704, 103);

        jLabelError.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 255, 255));
        jLabelError.setText("Report Error");
        add(jLabelError);
        jLabelError.setBounds(132, 410, 400, 50);

        jLabelScore.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelScore.setForeground(new java.awt.Color(255, 255, 255));
        jLabelScore.setText("Submit Score");
        add(jLabelScore);
        jLabelScore.setBounds(132, 280, 400, 50);

        jLabelScoreBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_mymatch_paralel.png"))); // NOI18N
        add(jLabelScoreBg);
        jLabelScoreBg.setBounds(66, 252, 655, 101);

        jLabelErrorBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_mymatch_paralel.png"))); // NOI18N
        add(jLabelErrorBg);
        jLabelErrorBg.setBounds(66, 385, 655, 101);
    }// </editor-fold>//GEN-END:initComponents

    public void refreshSize(Rectangle rtArea) {

        float rateW = Def.rateW;
        float rateH = Def.rateH;

        rtArea = ComUtil.getResize(rtArea, rateW, rateH);
        setBounds(rtArea);

        Rectangle rtTitle = jLabelTitle.getBounds();
        Rectangle rtTitleShow = jLabelTitleShow.getBounds();
        Rectangle rtLine = jLabelLine.getBounds();
        Rectangle rtOther = jLabelOther.getBounds();
        Rectangle rtYou = jLabelYou.getBounds();
        Rectangle rtScoreBg = jLabelScoreBg.getBounds();
        Rectangle rtScore = jLabelScore.getBounds();
        Rectangle rtScoreBtn = jButtonScore.getBounds();
        Rectangle rtError = jLabelError.getBounds();
        Rectangle rtErrorBg = jLabelErrorBg.getBounds();
        Rectangle rtErrorBtn = jButtonError.getBounds();

        rtTitle = ComUtil.getResize(rtTitle, rateW, rateH);
        rtTitleShow = ComUtil.getResize(rtTitleShow, rateW, rateH);
        rtLine = ComUtil.getResize(rtLine, rateW, rateH);
        rtOther = ComUtil.getResize(rtOther, rateW, rateH);
        rtYou = ComUtil.getResize(rtYou, rateW, rateH);
        rtScore = ComUtil.getResize(rtScore, rateW, rateH);
        rtScoreBg = ComUtil.getResize(rtScoreBg, rateW, rateH);
        rtScoreBtn = ComUtil.getResize(rtScoreBtn, rateW, rateH);
        rtError = ComUtil.getResize(rtError, rateW, rateH);
        rtErrorBg = ComUtil.getResize(rtErrorBg, rateW, rateH);
        rtErrorBtn = ComUtil.getResize(rtErrorBtn, rateW, rateH);
        rtTitle = ComUtil.getResize(rtTitle, rateW, rateH);

        jLabelTitle.setBounds(rtTitle);
        jLabelTitleShow.setBounds(rtTitleShow);
        jLabelLine.setBounds(rtLine);
        jLabelOther.setBounds(rtOther);
        jLabelYou.setBounds(rtYou);
        jLabelScore.setBounds(rtScore);
        jLabelScoreBg.setBounds(rtScoreBg);
        jButtonScore.setBounds(rtScoreBtn);
        jLabelError.setBounds(rtError);
        jLabelErrorBg.setBounds(rtErrorBg);
        jButtonError.setBounds(rtErrorBtn);

        // title image
        ImageIcon imgIcon = (ImageIcon)jLabelTitleShow.getIcon();
        Image image = imgIcon.getImage();
        Image image2 = image.getScaledInstance(jLabelTitleShow.getWidth(), jLabelTitleShow.getHeight(), Image.SCALE_SMOOTH);
        jLabelTitleShow.setIcon(new ImageIcon(image2));

        imgIcon = (ImageIcon)jLabelLine.getIcon();
        image = imgIcon.getImage();
        image2 = image.getScaledInstance(jLabelLine.getWidth(), jLabelLine.getHeight(), Image.SCALE_SMOOTH);
        jLabelLine.setIcon(new ImageIcon(image2));

        imgIcon = (ImageIcon)jLabelErrorBg.getIcon();
        image = imgIcon.getImage();
        image2 = image.getScaledInstance(jLabelErrorBg.getWidth(), jLabelErrorBg.getHeight(), Image.SCALE_SMOOTH);
        jLabelErrorBg.setIcon(new ImageIcon(image2));

        imgIcon = (ImageIcon)jLabelScoreBg.getIcon();
        image = imgIcon.getImage();
        image2 = image.getScaledInstance(jLabelScoreBg.getWidth(), jLabelScoreBg.getHeight(), Image.SCALE_SMOOTH);
        jLabelScoreBg.setIcon(new ImageIcon(image2));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonError;
    private javax.swing.JButton jButtonScore;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelErrorBg;
    private javax.swing.JLabel jLabelLine;
    private javax.swing.JLabel jLabelOther;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelScoreBg;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleShow;
    private javax.swing.JLabel jLabelYou;
    // End of variables declaration//GEN-END:variables

}
