/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContentTourPanel.java
 *
 * Created on Dec 28, 2019, 3:37:40 AM
 */

package mt.ui.panel;

import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import mt.util.ComUtil;
import mt.util.Def;

/**
 *
 * @author Administrator
 */
public class ContentTourPanel extends javax.swing.JPanel {
    public static final int DEF_PANEL_WIDTH = 1072;
    public static final int DEF_PANEL_HEIGHT = 1018;

    /** Creates new form ContentTourPanel */
    public ContentTourPanel() {
        initComponents();
        refreshSize(Def.RT_PANEL_CONTENT);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleShow = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 14, 26));
        setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Tournament List");
        add(jLabelTitle);
        jLabelTitle.setBounds(80, 34, 180, 40);

        jLabelTitleShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_titleshow.png"))); // NOI18N
        add(jLabelTitleShow);
        jLabelTitleShow.setBounds(52, 25, 390, 63);
    }// </editor-fold>//GEN-END:initComponents


    public void refreshSize(Rectangle rtArea) {

        float rateW = Def.rateW;
        float rateH = Def.rateH;

        rtArea = ComUtil.getResize(rtArea, rateW, rateH);
        setBounds(rtArea);

        Rectangle rtTitle = jLabelTitle.getBounds();
        Rectangle rtTitleShow = jLabelTitleShow.getBounds();


        rtTitle = ComUtil.getResize(rtTitle, rateW, rateH);
        rtTitleShow = ComUtil.getResize(rtTitleShow, rateW, rateH);

        jLabelTitle.setBounds(rtTitle);
        jLabelTitleShow.setBounds(rtTitleShow);

        // title image
        ImageIcon imgIcon = (ImageIcon)jLabelTitleShow.getIcon();
        Image image = imgIcon.getImage();
        Image image2 = image.getScaledInstance(jLabelTitleShow.getWidth(), jLabelTitleShow.getHeight(), Image.SCALE_SMOOTH);
        jLabelTitleShow.setIcon(new ImageIcon(image2));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleShow;
    // End of variables declaration//GEN-END:variables

}
