/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GamePanel.java
 *
 * Created on Dec 27, 2019, 5:31:36 AM
 */

package mt.ui.panel;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import mt.ui.control.CircleBorder;
import mt.ui.control.RoundBorder;
import mt.ui.control.RoundedCornerBorder;
import mt.util.ComUtil;
import mt.util.Def;

/**
 *
 * @author Administrator
 */
public class GamePanel extends javax.swing.JPanel {

    public static final int DEF_PANEL_WIDTH = 460;
    public static final int DEF_PANEL_HEIGHT = 122;

    /** Creates new form GamePanel */
    public GamePanel() {
        initComponents();
    }

    public GamePanel(Image imgIcon, String title, String strDate, int money) {
        initComponents();

        setGameIcon(imgIcon);
        setTitle(title);
        setDate(strDate);
        setMoney(money);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelIcon = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jLabelTroopy = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparatorBottom = new javax.swing.JSeparator();
        jButtonJoin = new javax.swing.JButton();

        setBackground(new java.awt.Color(2, 14, 26));
        setLayout(null);

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/game_broy.jpg"))); // NOI18N
        jLabelIcon.setText("jLabel1");
        jLabelIcon.setBorder(new RoundBorder());
        add(jLabelIcon);
        jLabelIcon.setBounds(10, 20, 80, 80);

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Fortnite Chanllange");
        add(jLabelTitle);
        jLabelTitle.setBounds(110, 16, 230, 25);

        jLabelDate.setFont(new java.awt.Font("Dialog", 0, 15));
        jLabelDate.setForeground(new java.awt.Color(155, 155, 155));
        jLabelDate.setText("4 Feb | 11 AM");
        add(jLabelDate);
        jLabelDate.setBounds(110, 44, 230, 23);

        jLabelMoney.setFont(new java.awt.Font("Dialog", 1, 20));
        jLabelMoney.setForeground(new java.awt.Color(245, 166, 35));
        jLabelMoney.setText("$ 5000");
        add(jLabelMoney);
        jLabelMoney.setBounds(150, 68, 140, 32);

        jLabelTroopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Trophy.png"))); // NOI18N
        jLabelTroopy.setText("jLabel5");
        add(jLabelTroopy);
        jLabelTroopy.setBounds(110, 74, 22, 22);
        add(jSeparator2);
        jSeparator2.setBounds(240, 72, 190, 0);
        add(jSeparatorBottom);
        jSeparatorBottom.setBounds(110, 119, 349, 3);

        jButtonJoin.setBackground(new java.awt.Color(2, 14, 26));
        jButtonJoin.setFont(new java.awt.Font("Dialog", 0, 18));
        jButtonJoin.setForeground(new java.awt.Color(170, 191, 53));
        jButtonJoin.setText("Join");
        jButtonJoin.setBorder(null);
        jButtonJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJoin.setOpaque(false);
        jButtonJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JoinButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JoinButtonMouseExited(evt);
            }
        });
        jButtonJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinActionPerformed(evt);
            }
        });
        add(jButtonJoin);
        jButtonJoin.setBounds(368, 30, 88, 34);
    }// </editor-fold>//GEN-END:initComponents

    private void JoinButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoinButtonMouseEntered
        // TODO add your handling code here:
        setColor(jButtonJoin);
    }//GEN-LAST:event_JoinButtonMouseEntered

    private void JoinButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoinButtonMouseExited
        // TODO add your handling code here:
        resetColor(jButtonJoin);
    }//GEN-LAST:event_JoinButtonMouseExited

    private void jButtonJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonJoinActionPerformed

    public void refreshSize(Rectangle rtArea) {
        float rateW = Def.rateW;
        float rateH = Def.rateH;

        rtArea = ComUtil.getResize(rtArea, rateW, rateH);
        setBounds(rtArea);

        Rectangle rtIcon = jLabelIcon.getBounds();
        Rectangle rtTitle = jLabelTitle.getBounds();
        Rectangle rtDate = jLabelDate.getBounds();
        Rectangle rtTroopy = jLabelTroopy.getBounds();
        Rectangle rtMoney = jLabelMoney.getBounds();

        rtIcon = ComUtil.getResize(rtIcon, rateW, rateH);
        rtTitle = ComUtil.getResize(rtTitle, rateW, rateH);
        rtDate = ComUtil.getResize(rtDate, rateW, rateH);
        rtTroopy = ComUtil.getResize(rtTroopy, rateW, rateH);
        rtMoney = ComUtil.getResize(rtMoney, rateW, rateH);

        jLabelIcon.setBounds(rtIcon);
        jLabelTitle.setBounds(rtTitle);
        jLabelDate.setBounds(rtDate);
        jLabelTroopy.setBounds(rtTroopy);
        jLabelMoney.setBounds(rtMoney);
        
        // image resize
        ImageIcon imgIcon = (ImageIcon)jLabelIcon.getIcon();
        Image image = imgIcon.getImage();
        Image image2 = image.getScaledInstance(jLabelIcon.getWidth(), jLabelIcon.getHeight(), Image.SCALE_SMOOTH);
        jLabelIcon.setIcon(new ImageIcon(image2));

        // troopy
        imgIcon = (ImageIcon)jLabelTroopy.getIcon();
        image = imgIcon.getImage();
        image2 = image.getScaledInstance(jLabelTroopy.getWidth(), jLabelTroopy.getHeight(), Image.SCALE_SMOOTH);
        jLabelTroopy.setIcon(new ImageIcon(image2));

    }

    public void setGameIcon(Image image) {
        jLabelIcon.setIcon(new ImageIcon(image));
    }

    public void setTitle(String title) {
        jLabelTitle.setText(title);
    }

    public void setDate(String strDate) {
        jLabelDate.setText(strDate);
    }

    public void setMoney(int money) {
        String strMoney = String.format("$%d", money);
        jLabelMoney.setText(strMoney);
    }

    ///////////////////////////////////////////////////
    // button action
    public void setColor(JButton Button)
    {
        Button.setForeground(new Color(2,14,26));
        Button.setBackground(new Color(170,191,53));
        //Button.setFont(new Font("Poor Richard", Font.PLAIN, 18));
    }
    public void resetColor(JButton Button)
    {
        Button.setForeground(new Color(170,191,53));
        Button.setBackground(new Color(2,14,26));
        //Button.setFont(new Font("Poor Richard", Font.PLAIN, 18));
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJoin;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTroopy;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparatorBottom;
    // End of variables declaration//GEN-END:variables

}
