/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mt.ui.panel;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author John
 */
public class MenuItemPanel extends javax.swing.JPanel {

    ImageIcon imageIcon;
    ImageIcon imageIconSelected;
    
    Color colorNormal = new Color(255,255,255);
    Color colorSel = new Color(170,191,53);
    int fontSize = 16;
    /**
     * Creates new form MenuItemPanel
     */
    public MenuItemPanel() {
        //initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIcon = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIcon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelIcon.setText("jLabel1");
        add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 30));

        jLabelText.setText("Dashboard");
        add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 30));
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        
        jLabelIcon = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        
        // background color into transparent
        setOpaque(true);
        setBackground(new Color(0,0,0,0) );
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        //setBackground(new Color(20,250,20) );
        
        jLabelIcon.setText("");
        jLabelText.setText("");
        jLabelBackground.setText("");
        
        jLabelText.setForeground(colorNormal);
        jLabelText.setFont(new java.awt.Font("Tahoma", 0, fontSize)); // NOI18N       
        
        
    }
    
    public void setPanelSize(int w, int h) {
        
        int itemh = h / 2;
        
        // icon
        jLabelIcon.setBounds(itemh/2, itemh/2, itemh, itemh);
        
        // content
        jLabelText.setBounds(itemh*2, itemh/2, w - itemh*2, itemh);
        
        // background
        jLabelBackground.setBounds(0, 0, w, h);         
        
        add(jLabelIcon);
        add(jLabelText);
        add(jLabelBackground);
        
        setLayout(null);
        
        jLabelBackground.setVisible(false);
        
    }
    
    public void setIcon(Image image, Image imageSel) {
        Image image2 = image.getScaledInstance(jLabelIcon.getWidth(), jLabelIcon.getHeight(), Image.SCALE_SMOOTH);
        Image imageSel2 = imageSel.getScaledInstance(jLabelIcon.getWidth(), jLabelIcon.getHeight(), Image.SCALE_SMOOTH);
        
        imageIcon = new ImageIcon(image2);
        imageIconSelected = new ImageIcon(imageSel2);
        
        jLabelIcon.setIcon(imageIcon);
    }
    
    public void setContent(String text) {
        jLabelText.setText(text);
    }
    
    public void setBackgroundImage(Image image) {        
        Image image2 = image.getScaledInstance(jLabelBackground.getWidth(), jLabelBackground.getHeight(), Image.SCALE_SMOOTH);
        jLabelBackground.setIcon(new ImageIcon(image2));        
    }
    
    public void selectItem(boolean bShow) {        
        jLabelBackground.setVisible(bShow);
        jLabelIcon.setIcon(null);
        
        if (bShow){
            jLabelIcon.setIcon(imageIconSelected);
            jLabelText.setForeground(colorSel);
        }
        else {
            jLabelIcon.setIcon(imageIcon);
            jLabelText.setForeground(colorNormal);
        }        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelText;
    // End of variables declaration//GEN-END:variables
}
