/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TitlePanel.java
 *
 * Created on Dec 27, 2019, 9:09:21 AM
 */

package mt.ui.panel;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import mt.ui.control.RoundedCornerBorder;
import mt.ui.control.RoundedPanel;
import mt.util.ComUtil;
import mt.util.Def;

/**
 *
 * @author Administrator
 */
public class TitlePanel extends javax.swing.JPanel {

    public static final int DEF_PANEL_WIDTH = 958;
    public static final int DEF_PANEL_HEIGHT = 236;

    /** Creates new form TitlePanel */
    public TitlePanel() {
        initComponents();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jLabelTop = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelPlayers = new javax.swing.JLabel();
        jPanelRight = new RoundedPanel(20);
        jLabelFilling = new javax.swing.JLabel();
        jLabelJoin = new javax.swing.JLabel();
        jLabelRight = new javax.swing.JLabel();

        setBackground(new java.awt.Color(4, 22, 36));
        setLayout(null);

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_dashboard_title.jpg"))); // NOI18N
        add(jLabelImage);
        jLabelImage.setBounds(0, 0, 236, 236);

        jLabelTop.setFont(new java.awt.Font("Arial", 0, 18));
        jLabelTop.setForeground(new java.awt.Color(137, 146, 152));
        jLabelTop.setText("Champion Series");
        jLabelTop.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabelTop);
        jLabelTop.setBounds(280, 20, 250, 30);

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 36));
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Halo Classic");
        add(jLabelTitle);
        jLabelTitle.setBounds(280, 60, 300, 50);

        jLabelDate.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabelDate.setForeground(new java.awt.Color(154, 161, 167));
        jLabelDate.setText("2nd Jan, 2021");
        add(jLabelDate);
        jLabelDate.setBounds(280, 120, 330, 30);

        jLabelPlayers.setFont(new java.awt.Font("Dialog", 1, 20));
        jLabelPlayers.setForeground(new java.awt.Color(245, 166, 35));
        jLabelPlayers.setText("2*2 players");
        add(jLabelPlayers);
        jLabelPlayers.setBounds(280, 180, 270, 30);

        jPanelRight.setBackground(new java.awt.Color(16, 31, 42));
        jPanelRight.setPreferredSize(new java.awt.Dimension(271, 236));
        jPanelRight.setLayout(null);

        jLabelFilling.setFont(new java.awt.Font("Dialog", 1, 16));
        jLabelFilling.setForeground(new java.awt.Color(55, 95, 39));
        jLabelFilling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFilling.setText("Filling Fast");
        jPanelRight.add(jLabelFilling);
        jLabelFilling.setBounds(130, 130, 110, 30);

        jLabelJoin.setFont(new java.awt.Font("Dialog", 1, 36));
        jLabelJoin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJoin.setText("Join");
        jLabelJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRight.add(jLabelJoin);
        jLabelJoin.setBounds(130, 70, 100, 40);

        jLabelRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ico_dashboard_title_right.jpg"))); // NOI18N
        jPanelRight.add(jLabelRight);
        jLabelRight.setBounds(-20, 0, 134, 236);

        add(jPanelRight);
        jPanelRight.setBounds(687, 0, 270, 236);
    }// </editor-fold>//GEN-END:initComponents

    public void refreshSize(Rectangle rtArea) {
        float rateW = Def.rateW;
        float rateH = Def.rateH;

        rtArea = ComUtil.getResize(rtArea, rateW, rateH);
        setBounds(rtArea);

        Rectangle rtImage = jLabelImage.getBounds();
        Rectangle rtTop = jLabelTop.getBounds();
        Rectangle rtTitle = jLabelTitle.getBounds();
        Rectangle rtDate = jLabelDate.getBounds();
        Rectangle rtPlayers = jLabelPlayers.getBounds();
        Rectangle rtRight = jLabelRight.getBounds();
        Rectangle rtJoin = jLabelJoin.getBounds();
        Rectangle rtFilling = jLabelFilling.getBounds();

        rtImage = ComUtil.getResize(rtImage, rateW, rateH);
        rtTop = ComUtil.getResize(rtTop, rateW, rateH);
        rtTitle = ComUtil.getResize(rtTitle, rateW, rateH);
        rtDate = ComUtil.getResize(rtDate, rateW, rateH);
        rtPlayers = ComUtil.getResize(rtPlayers, rateW, rateH);
        rtRight = ComUtil.getResize(rtRight, rateW, rateH);
        rtJoin = ComUtil.getResize(rtJoin, rateW, rateH);
        rtFilling = ComUtil.getResize(rtFilling, rateW, rateH);

        jLabelImage.setBounds(rtImage);
        jLabelTop.setBounds(rtTop);
        jLabelTitle.setBounds(rtTitle);
        jLabelDate.setBounds(rtDate);
        jLabelPlayers.setBounds(rtPlayers);
        jLabelRight.setBounds(rtRight);
        jLabelJoin.setBounds(rtJoin);
        jLabelFilling.setBounds(rtFilling);
        
        // image resize
        ImageIcon imgIcon = (ImageIcon)jLabelImage.getIcon();
        Image image = imgIcon.getImage();
        Image image2 = image.getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        jLabelImage.setIcon(new ImageIcon(image2));
    }

    @Override
    protected void paintComponent(Graphics g) {
        //super.paintComponent(g);
        Dimension arcs = new Dimension(Def.DEF_CORNER_RADIUS, Def.DEF_CORNER_RADIUS);
        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        //Draws the rounded panel with borders.
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
        graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelFilling;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelJoin;
    private javax.swing.JLabel jLabelPlayers;
    private javax.swing.JLabel jLabelRight;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JPanel jPanelRight;
    // End of variables declaration//GEN-END:variables

}
