/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mt.ui.panel;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author John
 */
public class TournamentPanel extends javax.swing.JPanel {
    
    JLabel jLabelTitle;
    public TournamentItemPanel[] itemPanels = new TournamentItemPanel[4];
    int itemCnt = 4;   
    /**
     * Creates new form TournamentPanel
     */
    public TournamentPanel() {
        //initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        setBackground(new Color(0,0,0,0));
        jLabelTitle = new JLabel();
        
        for (int i = 0; i < itemCnt; i++) {
            itemPanels[i] = new TournamentItemPanel();
        }  
        
        
        // font
        jLabelTitle.setText("Tournament List");
        jLabelTitle.setFont(new Font("Tahoma", 0, 22)); 
        jLabelTitle.setForeground(Color.white);
       
    }
    
    public void setPanelSize(int w, int h) {
        
        int titleH = h /4;
        jLabelTitle.setBounds(0,0, w/2, titleH);
        
        int gapW = w / 20;
        int itemLeft = 0;
        int botom = h / 6;
        int itemTop = titleH;
        int itemH = (h - titleH - botom) /2;
        int itemW = (w -gapW) /2;
        
        itemPanels[0].setBounds(itemLeft, itemTop, itemW, itemH);
        itemTop = itemTop + itemH;        
        itemPanels[1].setBounds(itemLeft, itemTop, itemW, itemH);
        itemLeft = itemLeft + gapW + itemW;
        itemPanels[2].setBounds(itemLeft, itemTop, itemW, itemH);
        itemTop = itemTop - itemH;
        itemPanels[3].setBounds(itemLeft, itemTop, itemW, itemH);  
        
        for (int i = 0; i < itemCnt; i++) {
            itemPanels[i].setPanelSize(itemW, itemH);
        }
        
        for (int i = 0; i < itemCnt; i++) {
            add(itemPanels[i]);
        }
        
        add(jLabelTitle);        
        
        setLayout(null);
        setVisible(true);
    }
    
    public void testSample() {
        itemPanels[0].setTitle("Fornite Chanllange");
        itemPanels[0].setDate("4 Feb | 11 AM");
        itemPanels[0].setMoney(5000);
        ImageIcon imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_broy.jpg"));
        itemPanels[0].setGameIcon(imgIcon.getImage());
        
        itemPanels[1].setTitle("Dota2");
        itemPanels[1].setDate("7 Feb | 1:30 PM");
        itemPanels[1].setMoney(15000);
        itemPanels[1].showSeperator(false);
        imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_dota2.jpg"));
        itemPanels[1].setGameIcon(imgIcon.getImage());
        
        itemPanels[2].setTitle("Fortnite Challange");
        itemPanels[2].setDate("4 Feb | 11 AM");
        itemPanels[2].setMoney(3500);
        itemPanels[2].showSeperator(false);
        imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_db1st.jpg"));
        itemPanels[2].setGameIcon(imgIcon.getImage());
        
        itemPanels[3].setTitle("Super Mario Bros");
        itemPanels[3].setDate("5 Feb | 1 PM");
        itemPanels[3].setMoney(2500);
        imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/game_super_mario.jpg"));
        itemPanels[3].setGameIcon(imgIcon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
