/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mt.ui.panel;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSeparator;

/**
 *
 * @author John
 */
public class TournamentItemPanel extends javax.swing.JPanel {
    public JLabel jLabelIcon;
    public JLabel jLabelTitle;
    public JLabel jLabelDate;
    public JLabel jLabelWin;
    public JLabel jLabelMoney;
    public JSeparator jSeparator;

    /**
     * Creates new form TournamentItemPanel
     */
    public TournamentItemPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void init() {
        setBackground(new Color(0,0,0,0));
        
        jLabelIcon = new JLabel();
        jLabelTitle = new JLabel();
        jLabelDate = new JLabel();
        jLabelWin = new JLabel();
        jLabelMoney = new JLabel();
        jSeparator = new JSeparator();
                
        // panel size
        setSize(456, 82);      
        
        // font
        jLabelTitle.setFont(new Font("Tahoma", 0, 18));
        jLabelTitle.setForeground(Color.white);
        
        jLabelDate.setFont(new Font("Tahoma", 0, 16));
        jLabelDate.setForeground(new Color(112,118,125));
        
        jLabelMoney.setFont(new Font("Tahoma", 1, 20));
        jLabelMoney.setForeground(new Color(245,166,35));
        
        jLabelWin.setHorizontalAlignment(JLabel.CENTER);
        jLabelWin.setVerticalAlignment(JLabel.CENTER);
        
        jSeparator.setBackground(new Color(50, 58,66));
        
    }
    
    public void setPanelSize(int w, int h) {
        // game icon
        jLabelIcon.setBounds(0, 0, h, h);
        
        int itemLeft = h + 25;
        int itemTop = 0;
        int itemH = h / 3;
        // game title        
        jLabelTitle.setBounds(itemLeft, itemTop, w/2, itemH);
        jLabelTitle.setText("Title");
        
        // date
        itemTop += itemH;                
        jLabelDate.setBounds(itemLeft, itemTop, w/2, itemH);
        
        // win icon
        itemTop += itemH;
        jLabelWin.setBounds(itemLeft, itemTop, itemH, itemH);
        setWinIcon(true);
        
        // money
        itemLeft = itemLeft + itemH + 15;
        jLabelMoney.setBounds(itemLeft, itemTop, w/3, itemH);
        
        // seperator
        itemLeft = jLabelTitle.getX();
        itemTop = h -3;
        jSeparator.setBounds(itemLeft, itemTop, w - itemLeft, 3);
        
        add(jLabelIcon);
        add(jLabelTitle);
        add(jLabelDate);
        add(jLabelWin);
        add(jLabelMoney);
        add(jSeparator);
        setLayout(null);
        setSize(w, h);
    }
    
    public void setGameIcon(Image image) {
        int h = getHeight();        
        Image image2 = image.getScaledInstance(h, h, Image.SCALE_SMOOTH);
        jLabelIcon.setIcon(new ImageIcon(image2));        
    }
    
    public void setWinIcon(boolean bShow) {
        jLabelWin.setVisible(bShow);
        
        if (bShow) {
            ImageIcon imgIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Trophy.png"));
            Image image = imgIcon.getImage();
            Image image2 = image.getScaledInstance(jLabelWin.getWidth()/3*2, jLabelWin.getHeight()/3*2, Image.SCALE_SMOOTH);
            jLabelWin.setIcon(new ImageIcon(image2));
        }         
        
    }
    
    public void setTitle(String title) {
        jLabelTitle.setText(title);
    }
    
    public void setDate(String date) {
        jLabelDate.setText(date);
    }
    
    public void setWinVisible(boolean bWin) {
        jLabelWin.setVisible(bWin);
    } 
    
    public void setMoney(int money) {
        String strMoney = String.format("$%d", money);
        jLabelMoney.setText(strMoney);
    }
    
    public void showSeperator(boolean bShow) {
        jSeparator.setVisible(bShow);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
